buildscript {
	dependencies {
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.workspace", version: "10.1.7"
	}

	repositories {
		mavenLocal()
		mavenCentral()
		maven {
			url "https://repository-cdn.liferay.com/nexus/content/groups/public"
		}

		maven {
			url "https://repository.liferay.com/nexus/content/groups/public"
		}
	}
}

apply plugin: "com.liferay.workspace"

include 'bom'
