plugins {
	id 'java-platform'
	id 'maven-publish'
}

repositories {
	mavenCentral()
}

ext.pomInfo = {
	delegate.licenses {
		delegate.license {
			delegate.name 'Unpublished Copyright SMC TREVISO SRL.'
			//delegate.url 'https://www.smc.it/licenses/XXXX.txt'
			delegate.distribution 'repo'
		}
	}
	delegate.developers {
		delegate.developer {
			delegate.name "maumar"
			delegate.organization "SMC Treviso srl"
		}
	}
}

def verboseMode = Boolean.valueOf(project.properties["bom.verbose.mode"])

if (!project.hasProperty('product.bom.package.name')) {
	ext.bomPackageName = project.getProperty('product.name')
}
else {
	ext.bomPackageName = project.getProperty('product.bom.package.name')
}
if (bomPackageName.trim().size() == 0) {
	throw new GradleException("Please define 'product.bom.package.name' or 'product.name' inside 'gradle.properties'")
}

publishing {
	afterEvaluate {
		repositories {
			maven {
				credentials {
					username project.properties['registryUsername']
					password project.properties['registryPassword']
				}

				if (registrySuffix.endsWith("-SNAPSHOT")) {
					url project.properties['nexus.snapshots.url']
				}
				else {
					url project.properties['nexus.releases.url']
				}
			}
		}

		publications {
			maven(MavenPublication) {
				version "${productVersion}${registrySuffix}"
				artifactId "${bomPackageName}.bom"

				project.ext.finalArtifact = "${group}:${artifactId}:${version}"
				//println "I will publish '${group}:${artifactId}:${version}'"

				def changedProjects = project.property('changedProjects')
				def boolean changesMode = Boolean.valueOf(project.property('changesMode'))

				Set deps = []
				Map resolvedDeps = [:]

				pom.withXml {
					asNode().children().last() + {
						resolveStrategy = Closure.DELEGATE_FIRST

						name "${productName} BoM"

						dependencyManagement {
							dependencies {
								println "--changesMode=${changesMode}"

								// All SubProjects

					rootProject.subprojects.each { prj ->
						if (!prj.subprojects.empty) return
						if (prj.path.startsWith(":bom") || prj.path.startsWith(":plugins-sdk")) return

						String artifactName = prj.property('archivesBaseName')

							if (changesMode && !changedProjects.contains(prj.path)) {
								def targetVersion = prj.hasProperty('originalVersion') ? prj.property('originalVersion') : prj.version

								if (verboseMode) {
											println "LR ${prj.group}:${artifactName}:${targetVersion}"
								}

										deps.add("${prj.group}:${artifactName}:${targetVersion}")
							}
									else {
										if (verboseMode) {
											println "LC ${prj.group}:${artifactName}:${prj.version}"
										}

										deps.add("${prj.group}:${artifactName}:${prj.version}")
							}
						}

								// Distribution Profiles dependencies

								rootProject.configurations.each { conf ->
									if (conf.name.equals("distBOM")) {
										return
									}
									else if (!conf.name.startsWith("dist") && !conf.name.startsWith("feature")) {
										return
					}

									def resolved = conf.getResolvedConfiguration()

									resolved.getLenientConfiguration().getFirstLevelModuleDependencies().each{ dep ->
										resolvedDeps["${dep.moduleGroup}:${dep.moduleName}"] = "${dep.moduleGroup}:${dep.moduleName}:${dep.moduleVersion}"
				}

									conf.dependencies.each { dep ->
										if (dep instanceof ExternalDependency) {
											String key = "${dep.group}:${dep.name}"

											if (resolvedDeps.containsKey(key)) {
												String value = resolvedDeps[key]

												if (verboseMode) {
													println "CE ${dep.group}:${dep.name}:${dep.version} -> ${value}"
			}
												deps.add("${value}")
		}
											else {
												println "NotResolved ${dep.group}:${dep.name}:${dep.version}"
	}
}
										else if (dep instanceof ProjectDependency) {
											ProjectDependency projectDependency = dep as ProjectDependency

											Project prj = projectDependency.getDependencyProject()

											String archivesBaseName = prj.properties["archivesBaseName"]
											String targetVersion = projectDependency.version

											if (changesMode && !changedProjects.contains(prj.path)) {
												targetVersion = prj.hasProperty('originalVersion') ? prj.property('originalVersion') : prj.version
												if (verboseMode) {
													println "CP ${dep.group}:${archivesBaseName}:${targetVersion}"
		}
											}
											else if (verboseMode) {
												println "CM ${dep.group}:${archivesBaseName}:${targetVersion}"
			}

											deps.add("${dep.group}:${archivesBaseName}:${targetVersion}")
										}
										else {
											println "	//??? ${dep}"
										}
									}
								}

								deps.each { dep ->
									String[] parts = dep.split(":")

									dependency {
										groupId "${parts[0]}"
										artifactId "${parts[1]}"
										version "${parts[2]}"
									}
			}

				}
			}
					}
				}
			}
		}
	}
}

task publishLog() {
	doLast {
		def finalArtifact = project.property('finalArtifact')
		println "I will publish '${finalArtifact}'"
	}
}

publishToMavenLocal.dependsOn(publishLog);

publish.dependsOn(publishLog);
